$(document).ready(function(){
	//nav我的淘宝标题的二级菜单
	$(".nav_myTao").hover(function(){
		$(this).css({
			"background":"#fff"
			
		}).find(".nav-myTao-nav").show();
	},function(){
		$(this).css({
			"background":"#f5f5f5"
		}).find(".nav-myTao-nav").hide();
	});
	$(".nav_collection").hover(function(){
		$(this).css({
			"background":"#fff"
		}).find(".nav-myTao-nav").show();
	},function(){
		$(this).css({
			"background":"#f5f5f5"
		}).find(".nav-myTao-nav").hide();
	})
})